apiVersion: v1
kind: ConfigMap
metadata:
  name: template-json
data:
  template.json: |
    {
      "index_patterns": [ "fluentd-*" ],
      "settings": {
          "index": {
            "lifecycle": {
              "name": "fluentd-log-rotation",
              "rollover_alias": "fluentd"
            },
            "number_of_replicas": "0"
          }
      },
      "aliases": {
        "fluentd": {}
      }
    }
