apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.12.0
        resources:
          requests:
            memory: 1G
            cpu: 500m
          limits:
            memory: 2G
            cpu: 1000m
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml 
      volumes:
      - name: kibana-config
        configMap:
          defaultMode: 420
          name: kibana-config
