apiVersion: v1
kind: ConfigMap
metadata:
  name: elastisearch-config
data:
  elasticsearch.yml: |
    cluster.name: blt
    node.name: master
    path.data: /var/lib/elastisearch
    path.logs: /var/log/elastisearch
    network.host: [_local_, _site_]
    cluster.initial_master_nodes: ["master"]
    #action.destructive_requires_name: true
    node.master: true
    node.data: true
    node.ingest: true
    node.ml: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastisearch-jvm-config
data:
  jvm.options: |
    -Xms2g
    -Xmx2g
    8-13:-XX:+UseConcMarkSweepGC
    8-13:-XX:CMSInitiatingOccupancyFraction=75
    8-13:-XX:+UseCMSInitiatingOccupancyOnly
    14-:-XX:+UseG1GC
    -Djava.io.tmpdir=${ES_TMPDIR}
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=data
    -XX:ErrorFile=logs/hs_err_pid%p.log
    8:-XX:+PrintGCDetails
    8:-XX:+PrintGCDateStamps
    8:-XX:+PrintTenuringDistribution
    8:-XX:+PrintGCApplicationStoppedTime
    8:-Xloggc:logs/gc.log
    8:-XX:+UseGCLogFileRotation
    8:-XX:NumberOfGCLogFiles=32
    8:-XX:GCLogFileSize=64m
    9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
