apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastisearch
  template:
    metadata:
      labels:
        app: elastisearch
    spec:
      containers:
      - name: elastisearch
        image: elasticsearch:7.12.0
        resources:
          requests:
            memory: 1G
            cpu: 500m
          limits:
            memory: 3G
            cpu: 2000m
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: elastisearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elastisearch-jvm-config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        - name: elastisearch-data
          mountPath: /var/lib/elastisearch
        - name: elastisearch-logs
          mountPath: /var/log/elastisearch
      volumes:
      - name: elastisearch-config
        configMap:
          defaultMode: 420
          name: elastisearch-config
      - name: elastisearch-jvm-config
        configMap:
          defaultMode: 420
          name: elastisearch-jvm-config
      - name: elastisearch-data
        emptyDir: {}
      - name: elastisearch-logs
        emptyDir: {}
