apiVersion: v1
kind: Service
metadata:
  name: elastisearch-svc
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elastisearch

---
apiVersion: v1
kind: Service
metadata:
  name: elastisearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elastisearch
