apiVersion: v1
kind: ConfigMap
metadata:
  name: es-template
data:
  template.json: |-
    {
        "index_patterns": [
            "logstash-default*"
        ],
        "settings": {
            "index": {
                "number_of_replicas": "0"
            }
        }
    }