apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: {{ .Values.service.protocol }}
  - name: transport
    port: {{ .Values.service.transportPort }}
    targetPort: {{ .Values.service.transportPort }}
    protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
